### ISSUE TITLE
The chromedriver-helper gem is out of support

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/suspenders#1030]
Suspenders’ JavaScript driver generator adds the chromedriver-helper gem, [which is out of support](https://github.com/flavorjones/chromedriver-helper/blob/master/README.md):

https://github.com/thoughtbot/suspenders/blob/91b4fcff26034903af0ff17214003569a076d7bf/lib/suspenders/generators/js_driver_generator.rb#L7

The folks behind chromedriver-helper suggest using the [webdrivers gem](https://github.com/titusfortner/webdrivers), instead.

**Comment by gnclmorais** [comment]
I’m looking into setting this up on suspenders, but I’m having a hard time running a local version of this gem (with `webdrivers` instead of `chromedriver-helper`) to setup a new project… It tries to run suspenders commands but I keep running into:
```
…
       force  config/puma.rb
Copying miscellaneous support files
      create  config/initializers/errors.rb
      create  config/initializers/json_encoding.rb
Setting up database
       force  config/database.yml
         run  bundle exec rails db:create db:migrate
Database 'test01_development' already exists
Database 'test01_test' already exists
         run  spring stop from "."
Traceback (most recent call last):
	2: from /Users/goncalomorais/.rbenv/versions/2.6.5/bin/spring:23:in `<main>'
	1: from /Users/goncalomorais/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
/Users/goncalomorais/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path': can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
    generate  suspenders:profiler
       rails  generate suspenders:profiler
Traceback (most recent call last):
	3: from bin/rails:3:in `<main>'
	2: from bin/rails:3:in `require_relative'
	1: from /Users/goncalomorais/Development/__playground/suspenders-projects/test01/config/boot.rb:4:in `<top (required)>'
/Users/goncalomorais/Development/__playground/suspenders-projects/test01/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
    generate  suspenders:json
       rails  generate suspenders:json
Traceback (most recent call last):
	3: from bin/rails:3:in `<main>'
	2: from bin/rails:3:in `require_relative'
	1: from /Users/goncalomorais/Development/__playground/suspenders-projects/test01/config/boot.rb:4:in `<top (required)>'
/Users/goncalomorais/Development/__playground/suspenders-projects/test01/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
…
```
Any idea how to go around this?

**Comment by composerinteralia** [comment]
Did you try to run suspenders multiple times for an app named `test01`? What happens if you try `test02` instead? You may also want to clean up the database if you don't need it anymore (e.g. `echo "DROP DATABASE test01_development" | psql`)
