### ISSUE TITLE
suspenders my_project  - Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)

### ISSUE THREAD

**Issue by klueless-io** [thoughtbot/suspenders#1101]
I'm following the instructions in Readme to create a new project using Suspenders and getting this error using both Ruby 2.7.6 and Ruby 3.1.1

Is there some kind of configuration that I need to do before using `suspenders`

```bash
cd /Users/my_user/dev
suspenders my_project

# Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
```

```
Traceback (most recent call last):
        8: from /Users/my_user/.asdf/installs/ruby/2.7.6/bin/suspenders:23:in `<main>'
        7: from /Users/my_user/.asdf/installs/ruby/2.7.6/bin/suspenders:23:in `load'
        6: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/suspenders-1.56.0/bin/suspenders:28:in `<top (required)>'
        5: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:207:in `definition'
        4: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:83:in `configure'
        3: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:652:in `configure_gem_home_and_path'
        2: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:97:in `bundle_path'
        1: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:298:in `root'
/Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/shared_helpers.rb:15:in `root': Could not locate Gemfile (Bundler::GemfileNotFound)
        8: from /Users/my_user/.asdf/installs/ruby/2.7.6/bin/suspenders:23:in `<main>'
        7: from /Users/my_user/.asdf/installs/ruby/2.7.6/bin/suspenders:23:in `load'
        6: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/suspenders-1.56.0/bin/suspenders:28:in `<top (required)>'
        5: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:207:in `definition'
        4: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:83:in `configure'
        3: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:652:in `configure_gem_home_and_path'
        2: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:97:in `bundle_path'
        1: from /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:297:in `root'
/Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler.rb:301:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
```

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.6
  - RUBY VERSION: 2.7.6 (2022-04-12 patchlevel 219) [x86_64-darwin21]
  - INSTALLATION DIRECTORY: /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /Users/my_user/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/my_user/.asdf/installs/ruby/2.7.6/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/my_user/.asdf/installs/ruby/2.7.6/bin
  - SPEC CACHE DIRECTORY: /Users/my_user/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/my_user/.asdf/installs/ruby/2.7.6/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-21
  - GEM PATHS:
     - /Users/my_user/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0
     - /Users/my_user/.gem/ruby/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/my_user/.asdf/installs/ruby/2.7.6/bin
     - /usr/local/opt/openssl@1.1/bin
     - /Users/my_user/.asdf/shims
     - /Users/my_user/.asdf/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/go/bin
     - /usr/local/MacGPG2/bin
     - /usr/local/share/dotnet
     - ~/.dotnet/tools
     - /Library/Apple/usr/bin
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /usr/local/opt/openssl@1.1/bin
     - /Users/my_user/Library/Python/3.9/bin
     - /Users/my_user/.dotnet/tools
     - /Users/my_user/.gem/ruby/2.7.0/bin
     - /usr/local/opt/fzf/bin
     - /Users/my_user/Library/Python/3.9/bin
     - /Users/my_user/.dotnet/tools
     - /Users/my_user/.gem/ruby/2.7.0/bin
```

**Comment by helpotters** [comment]
Also running into this issue. I updated bundler, ran `gem update`. No dice.

**Comment by thiagoa** [comment]
@klueless-io Thank you so much for reporting this error. There was a critical problem with the previous release that was fixed in [this pull request](https://github.com/thoughtbot/suspenders/pull/1102).

We've yanked the previous version and published a new one with the fix. Would you run `gem update suspenders` and give it another try? I'm closing this issue but feel free to comment and/or reopen it if needed.

**Comment by helpotters** [comment]
It works perfectly now with my aforementioned setup. Thanks a ton!
