### ISSUE TITLE
shoulda-matchers not working after initial setup of project

### ISSUE THREAD

**Issue by stefanhendriks** [thoughtbot/suspenders#557]
Because of https://github.com/thoughtbot/shoulda/issues/203 I tried creating a new project using suspenders. After setting up a new suspenders project and adding a model `developer` (using `rails g model developer`). Then add a 'name' field. I then add a model test that `validates_presence_of` the name field. Which looks like:
```
require 'rails_helper'

RSpec.describe Developer, :type => :model do
  validates_presence_of :name
end

```

Running just `rspec` gives me:
```
/Users/shendriks/projects/fundynamic/regexed/spec/models/developer_spec.rb:4:in `block in <top (required)>': undefined method `validates_presence_of' for RSpec::ExampleGroups::Developer:Class (NoMethodError)
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:325:in `module_exec'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:325:in `subclass'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:219:in `block in define_example_group_method'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/dsl.rb:41:in `block in expose_example_group_alias'
	from /Users/shendriks/projects/fundynamic/regexed/spec/models/developer_spec.rb:3:in `<top (required)>'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /Users/shendriks/.rvm/gems/ruby-2.2.1@regexed/bin/rspec:23:in `load'
```

Gemfile:
```
source "https://rubygems.org"

ruby "2.2.1"

gem "airbrake"
gem "autoprefixer-rails"
gem "bourbon", "~> 4.2.0"
gem "coffee-rails", "~> 4.1.0"
gem "delayed_job_active_record"
gem "email_validator"
gem "flutie"
gem "high_voltage"
gem "i18n-tasks"
gem "jquery-rails"
gem "neat", "~> 1.7.0"
gem "newrelic_rpm", ">= 3.9.8"
gem "normalize-rails", "~> 3.0.0"
gem "pg"
gem "rails", "4.2.1"
gem "recipient_interceptor"
gem "refills"
gem "sass-rails", "~> 5.0"
gem "simple_form"
gem "title"
gem "uglifier"
gem "unicorn"

group :development do
  gem "spring"
  gem "spring-commands-rspec"
  gem "web-console"
end

group :development, :test do
  gem "awesome_print"
  gem "bundler-audit", require: false
  gem "byebug"
  gem "dotenv-rails"
  gem "factory_girl_rails"
  gem "pry-rails"
  gem "rspec-rails", "~> 3.1.0"
end

group :test do
  gem "capybara-webkit", ">= 1.2.0"
  gem "database_cleaner"
  gem "formulaic"
  gem "launchy"
  gem "shoulda-matchers", require: false
  gem "simplecov", require: false
  gem "timecop"
  gem "webmock"
end

group :staging, :production do
  gem "rack-timeout"
end
```

Ruby version:
```
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
```

Using RVM version:
```
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

**Comment by tute** [comment]
Did https://github.com/thoughtbot/shoulda/issues/203#issuecomment-94197346 solve your issue?

**Comment by stefanhendriks** [comment]
Yes, the latest comment pointed out an obvious error from my side. Don't ask me how I got to that point, but it works. And so everything works now as expected. Thanks! :+1: :dancer:
