### ISSUE TITLE
SimpleForm dependency is not setup correctly with BUNDLE_PATH option set

### ISSUE THREAD

**Issue by tute** [thoughtbot/suspenders#768]
When running suspenders with `BUNDLE_PATH` option, then suspenders has the simple_form gem installed, but not the generated application, which also needs it. When generating an app with this configuration (command: `bundle exec ruby -S bin/suspenders test-`date +"%Y%m%d%H%M%S"`--path=~/Sites/opensource/suspenders/suspenders`), you will see something like:

```
[...]
Installing title 0.0.7
Bundle complete! 45 Gemfile dependencies, 107 gems now installed.
Bundled gems are installed into ./.bundle/vendor.
Post-install message from webmock:

  WebMock 2.0 has some breaking changes. Please check the CHANGELOG: https://goo.gl/piDGLu

         run  bundle exec rails generate simple_form:install
W, [2016-05-20T13:46:38.874576 #84095]  WARN -- : [SKYLIGHT] [0.10.3] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
SimpleForm 3 supports Bootstrap and Zurb Foundation 5. If you want a configuration that is compatible with one of these frameworks, then please re-run this generator with --bootstrap or --foundation as an option.
      create  config/initializers/simple_form.rb
       exist  config/locales
      create  config/locales/simple_form.en.yml
      create  lib/templates/erb/scaffold/_form.html.erb
Setting up the development environment
      insert  config/environments/test.rb
      insert  config/environments/development.rb
      insert  config/environments/development.rb
      insert  config/application.rb
       force  bin/setup
         run  chmod a+x bin/setup from "."
      create  lib/tasks/dev.rake
      insert  config/application.rb
        gsub  config/environments/development.rb
        gsub  config/environments/test.rb
      insert  config/application.rb
Setting up the test environment
      create  spec/support/factory_girl.rb
      create  spec/factories.rb
      create  .hound.yml
    generate  rspec:install
/Users/tutec/Sites/opensource/suspenders/suspenders/test-20160520134320/config/initializers/simple_form.rb:2:in `<top (required)>': uninitialized constant SimpleForm (NameError)
        from /Users/tutec/Sites/opensource/suspenders/suspenders/.bundle/vendor/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initialize
[...]
```

We want simple_form to be installed before needing it in the generated app.

Pairing with @teoljungberg. Thanks for your help triaging this.

**Comment by mike-burns** [comment]
Fixed in 588a1eaad34f483cff38c5f26c211f6ecf0bd672.
