### ISSUE TITLE
Can't create app

### ISSUE THREAD

**Issue by AndreiMotinga** [thoughtbot/suspenders#852]
Can't generate new app. 

```sh
➜  dev ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
➜  dev rbenv global 2.4.0
➜  dev rbenv global 2.4.0
➜  dev gem install suspenders
Successfully installed suspenders-1.44.0
1 gem installed
➜  dev suspenders suspenders ez_api \
  --heroku true \
  --heroku-flags "--region eu --addons sendgrid"
/usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:2278:in `check_version_conflict': can't activate activesupport-5.1.2, already activated activesupport-5.0.4 (Gem::LoadError)
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:1404:in `activate'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:88:in `each'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent.rb:15:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.4/lib/active_support/logger_silence.rb:3:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.4/lib/active_support/logger.rb:1:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.4/lib/active_support.rb:27:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.4/lib/rails/generators.rb:6:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/suspenders-1.44.0/lib/suspenders/generators/app_generator.rb:1:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/suspenders-1.44.0/lib/suspenders.rb:2:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/suspenders-1.44.0/bin/suspenders:7:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.4.0/bin/suspenders:22:in `load'
	from /usr/local/opt/rbenv/versions/2.4.0/bin/suspenders:22:in `<main>'
```

**Comment by AndreiMotinga** [comment]
`gem cleanup` solved it
