### ISSUE TITLE
Bizarre error from Addressable::URI on Heroku bare deploy

### ISSUE THREAD

**Issue by vcavallo** [thoughtbot/suspenders#940]
I just deployed what is little more than a bare suspenders repo to Heroku and am getting an error on every route which I've never seen before and yields next to zero results on google, github issues, etc. This app works fine locally. Error:

```
2018-10-03T01:30:07.355811+00:00 app[web.1]: I, [2018-10-03T01:30:07.355598 #22]  INFO -- : [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] Started GET "/lawyers.json" for 68.224.196.36 at 2018-10-03 01:30:07 +0000
2018-10-03T01:30:07.358617+00:00 app[web.1]: F, [2018-10-03T01:30:07.358536 #22] FATAL -- : [99add6df-2ac1-45d4-a10d-aa8b592fe4fd]
2018-10-03T01:30:07.358748+00:00 app[web.1]: F, [2018-10-03T01:30:07.358679 #22] FATAL -- : [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] Addressable::URI::InvalidURIError (Invalid character in host: 'https://people-protector-staging.herokuapp.com'):
2018-10-03T01:30:07.358835+00:00 app[web.1]: F, [2018-10-03T01:30:07.358773 #22] FATAL -- : [99add6df-2ac1-45d4-a10d-aa8b592fe4fd]
2018-10-03T01:30:07.358986+00:00 app[web.1]: F, [2018-10-03T01:30:07.358898 #22] FATAL -- : [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/addressable-2.5.2/lib/addressable/uri.rb:2438:in `validate'
2018-10-03T01:30:07.358989+00:00 app[web.1]: [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1128:in `host='
2018-10-03T01:30:07.358991+00:00 app[web.1]: [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:77:in `new_url'
2018-10-03T01:30:07.358993+00:00 app[web.1]: [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:53:in `headers'
2018-10-03T01:30:07.358994+00:00 app[web.1]: [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:32:in `response'
2018-10-03T01:30:07.358996+00:00 app[web.1]: [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host.rb:21:in `call'

[ remainder trimmed]
```

The host is https://people-protector-staging.herokuapp.com/lawyers.json ... I can't see what is possibly wrong with this URI. The same issue arises when requesting the root URL.
I've tried turning off `force_ssl` and visiting the http version - no luck.

I opened an issue with Addressable here: https://github.com/sporkmonger/addressable/issues/316

Any ideas much appreciated. (I realize suspenders is not a DevOps debugging community 😆)
Thanks!

**Comment by vcavallo** [comment]
Update: I've deployed this app to a dev server of mine (under a subdomain) that has numerous other rails apps on it. If I hit it with curl from _inside the vps_ it works fine either via localhost or the url (dev.my-app-name-here.my-domain.com). But If I hit the same url with curl from another machine I get  `curl: (6) Could not resolve host`. If I try a domain of a different rails app on the same server it works just fine.
I'm irrationally convinced that there is something odd with the configs of suspenders that is effecting requests from _outside_ whatever machine it is running on (heroku, my server) but not the host machine itself (my local dev setup, via ssh into the aforementioned server). Huh?

**Comment by vcavallo** [comment]
Doh... For anyone coming after me: when setting your `ASSET_HOST` and `APPLICATION_HOST` key values, _do not include the protocol_. 

- `your-app-name.herokuapp.com` <-- good. 
- `https://your-app-name.herokuapp.com` <-- bad.
