### ISSUE TITLE
failing tests due to incorrect SQLite version

### ISSUE THREAD

**Issue by dimanyc** [thoughtbot/suspenders#966]
When I run the test suite locally, I am getting 7 failures caused by the sqlite3 adapter version mismatch. 
```shell 
  1) suspenders:json generates the Gemfile for JSON parsing
     Failure/Error: expect("Gemfile").to match_contents(%r{gem .oj.})
       expected "Gemfile" to match contents /gem .oj./
     # ./spec/features/json_spec.rb:7:in `block (2 levels) in <top (required)>'

  2) suspenders:production:deployment generates the configuration for a production deployment
     Failure/Error: expect("bin/deploy").to exist_as_a_file
       expected "bin/deploy" to exist as a file
     # ./spec/features/production/deployment_spec.rb:9:in `block (2 levels) in <top (required)>'

  3) suspenders:production:email generates the configuration for a production email deployment
     Failure/Error: contents = IO.read(File.join(project_path, filename))

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/---/Desktop/ruby_sandbox/suspenders/tmp/dummy_app/config/smtp.rb
     # ./spec/support/match_contents_matcher.rb:3:in `read'
     # ./spec/support/match_contents_matcher.rb:3:in `block (2 levels) in <top (required)>'
     # ./spec/features/production/email_spec.rb:7:in `block (2 levels) in <top (required)>' 

  4) suspenders:production:email destroys the configuration for a production email deployment
     Failure/Error: json = JSON.parse(IO.read(filepath), symbolize_names: true)

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/---Desktop/ruby_sandbox/suspenders/tmp/dummy_app/app.json
     # ./spec/support/contain_json_matcher.rb:11:in `read'
     # ./spec/support/contain_json_matcher.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/features/production/email_spec.rb:38:in `block (2 levels) in <top (required)>'

  5) suspenders:production:manifest generates the manifest for a production build
     Failure/Error: json = JSON.parse(IO.read(filepath), symbolize_names: true)

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/---/Desktop/ruby_sandbox/suspenders/tmp/dummy_app/app.json
     # ./spec/support/contain_json_matcher.rb:11:in `read'
     # ./spec/support/contain_json_matcher.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/features/production/manifest_spec.rb:7:in `block (2 levels) in <top (required)>'

  6) suspenders:production:manifest destroys the manifest for a production build
     Failure/Error: json = JSON.parse(IO.read(filepath), symbolize_names: true)

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/---/Desktop/ruby_sandbox/suspenders/tmp/dummy_app/app.json
     # ./spec/support/contain_json_matcher.rb:11:in `read'
     # ./spec/support/contain_json_matcher.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/features/production/manifest_spec.rb:23:in `block (2 levels) in <top (required)>'

  7) suspenders:staging:pull_requests generates the configuration for Heroku pipeline review apps
     Failure/Error:
       expect("config/environments/production.rb").to \
         match_contents(%r{HEROKU_APP_NAME})

       expected "config/environments/production.rb" to match contents /HEROKU_APP_NAME/
     # ./spec/features/staging/pull_requests_spec.rb:7:in `block (2 levels) in <top (required)>'
```

and the trace is:
```shell
.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile. (LoadError)
	from /Users/---/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:12:in `<main>'
	from /Users/---/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
```

As pointed out in this PR: https://github.com/thoughtbot/factory_bot_rails/pull/318, the current `rails new` generator defaults to the most recent version of SQLite, which is incompatible with Rails.

**Comment by composerinteralia** [comment]
As mentioned in https://github.com/thoughtbot/suspenders/pull/967, this sorted itself out.
